// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtaTc_7V0EmRFlLCbL4Sh4RGYl9M7pr7M',
    appId: '1:282887394151:web:51633c1afa0004962e95c2',
    messagingSenderId: '282887394151',
    projectId: 'laptopharbor-9861c',
    authDomain: 'laptopharbor-9861c.firebaseapp.com',
    storageBucket: 'laptopharbor-9861c.firebasestorage.app',
    measurementId: 'G-3WS3X13KSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdqb9xjb_l0l33jXrdkzVSFfEM3JLueG4',
    appId: '1:282887394151:android:6a830113f6ba83db2e95c2',
    messagingSenderId: '282887394151',
    projectId: 'laptopharbor-9861c',
    storageBucket: 'laptopharbor-9861c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbdFORE4WORr6anHgKNMPMlrhC4Xt_7Yk',
    appId: '1:282887394151:ios:7a82110baf7cac722e95c2',
    messagingSenderId: '282887394151',
    projectId: 'laptopharbor-9861c',
    storageBucket: 'laptopharbor-9861c.firebasestorage.app',
    iosBundleId: 'com.example.laptopharbor',
  );

}