// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3e0fFZnRzrILIgLvX5Z8U6_2mcUAK7QE',
    appId: '1:484062572276:web:0da97ca9e0722d7ba6f8a1',
    messagingSenderId: '484062572276',
    projectId: 'laptopharbor-97b44',
    authDomain: 'laptopharbor-97b44.firebaseapp.com',
    storageBucket: 'laptopharbor-97b44.firebasestorage.app',
    measurementId: 'G-8Z8BJDG8GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Gc9KMwt6HK9sAmcQlurpgrsdB3PrOVE',
    appId: '1:484062572276:android:d26a2ccac8720fd2a6f8a1',
    messagingSenderId: '484062572276',
    projectId: 'laptopharbor-97b44',
    storageBucket: 'laptopharbor-97b44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0zn_Ycm_wnCE8uAYxeVsDVg--TSlnos',
    appId: '1:484062572276:ios:3e1106c64d5f056da6f8a1',
    messagingSenderId: '484062572276',
    projectId: 'laptopharbor-97b44',
    storageBucket: 'laptopharbor-97b44.firebasestorage.app',
    iosBundleId: 'com.example.laptopharbor',
  );
}
